import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css'
import clsx from 'clsx'
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner"
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Project Rdd",
  description: "Generated by create next app",
};
import { Terminal } from "lucide-react"

import {
  Alert,
  AlertDescription,
  AlertTitle,
} from "@/components/ui/alert"


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className='h-full' suppressHydrationWarning>
      <body className={clsx(inter.className, 'flex min-h-screen w-full flex-col bg-muted/40')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <header className="flex w-full max-w-full flex-row items-center justify-end border-b-2 border-b-accent">
            <NavBar />
          </header >
          <main className='flex size-full flex-col items-center'>
            <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
              <Alert>
                <Terminal className="h-4 w-4" />
                <AlertTitle>Version de développement !</AlertTitle>
                <AlertDescription>
                  Cette version est une preuve de concept et n&aspo;est pas encore prête pour une utilisation en production. Vous ne devez pas l&apos;utiliser pour des données réelles.
                </AlertDescription>
              </Alert>
            </div>

            {children}
            <Toaster />
          </main>
        </ThemeProvider>
      </body>
    </html >
  );
}
