import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css'
import clsx from 'clsx'
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner"
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Project Rdd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className='h-full' suppressHydrationWarning>
      <body className={clsx(inter.className, 'flex min-h-screen w-full flex-col bg-muted/40')}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <header className="flex w-full max-w-full flex-row items-center justify-end border-b-2 border-b-accent">
            <NavBar />
          </header >
          <main className='flex size-full flex-col items-center'>
            {children}
            <Toaster />
          </main>
        </ThemeProvider>
      </body>
    </html >
  );
}
