-- CreateTable
CREATE TABLE "WorkContract" (
    "numSS" TEXT NOT NULL,
    "dsnId" TEXT NOT NULL,
    "contractId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "establishmentId" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "status" TEXT NOT NULL,
    "retirement" TEXT NOT NULL,
    "pcs" TEXT NOT NULL,
    "pcsBis" TEXT NOT NULL,
    "employementLabel" TEXT NOT NULL,
    "contract" TEXT NOT NULL,
    "publicDispPolitic" TEXT NOT NULL,
    "contractEndDate" TIMESTAMP(3) NOT NULL,
    "DNACodeUnitTime" TEXT NOT NULL,
    "DSNWorkQuotaEstablishment" TEXT NOT NULL,
    "DSNWorkQuotaWorkContract" TEXT NOT NULL,
    "workTime" TEXT NOT NULL,
    "ss" TEXT NOT NULL,
    "idcc" TEXT NOT NULL,
    "malakoff" TEXT NOT NULL,
    "estabWorkPlace" TEXT NOT NULL,
    "vieillesse" TEXT NOT NULL,
    "pattern" TEXT NOT NULL,
    "vacation" TEXT NOT NULL,
    "rateProfessionalFess" TEXT NOT NULL,
    "foreigner" TEXT NOT NULL,
    "exclusionDsn" TEXT NOT NULL,
    "statusEmployment" TEXT NOT NULL,
    "unemployment" TEXT NOT NULL,
    "idPublicEmployer" TEXT NOT NULL,
    "methodUnemployment" TEXT NOT NULL,
    "joiningDate" TIMESTAMP(3) NOT NULL,
    "denunciationDate" TIMESTAMP(3) NOT NULL,
    "dateManagementAgreement" TIMESTAMP(3) NOT NULL,
    "idAgreement" TEXT NOT NULL,
    "healthRiskDelegate" TEXT NOT NULL,
    "multipleJobCode" TEXT NOT NULL,
    "multipleEmployerCode" TEXT NOT NULL,
    "workAccidentRisk" TEXT NOT NULL,
    "idWorkAccidentRisk" TEXT NOT NULL,
    "positionCollectiveAgreement" TEXT NOT NULL,
    "apecita" TEXT NOT NULL,
    "rateAt" TEXT NOT NULL,
    "contributingFullTime" TEXT NOT NULL,
    "tip" TEXT NOT NULL,
    "useEstablishmentId" TEXT NOT NULL,
    "livePerfomances" TEXT NOT NULL,
    "licences" TEXT NOT NULL,
    "showId" TEXT NOT NULL,
    "showrunner" TEXT NOT NULL,
    "fpPcsfpPcs" TEXT,
    "typePosition" TEXT,
    "fpQuotite" TEXT,
    "partTimeWork" TEXT,
    "serviceCode" TEXT,
    "fpIndice" TEXT,
    "fpIndiceMaj" TEXT,
    "NBI" TEXT,
    "indiceOriginal" TEXT,
    "article15" TEXT,
    "oldEstablishmentId" TEXT,
    "oldIndice" TEXT,
    "SPP" TEXT,
    "contractualHours" TEXT,
    "secondment" TEXT,
    "browsing" TEXT,
    "activityDutyRate" TEXT,
    "payLevel" TEXT,
    "echelon" TEXT,
    "coefficient" TEXT,
    "boeth" TEXT,
    "addPublicPolicy" TEXT,
    "arrangement" TEXT,
    "finaly" TEXT,
    "navy" TEXT,
    "navyCode" TEXT,
    "activityRate" TEXT,
    "grade" TEXT,
    "cti" TEXT,
    "finess" TEXT,
    "dateStart" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT NOT NULL,

    CONSTRAINT "WorkContract_pkey" PRIMARY KEY ("dsnId","numSS","contractId")
);

-- AddForeignKey
ALTER TABLE "WorkContract" ADD CONSTRAINT "WorkContract_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkContract" ADD CONSTRAINT "WorkContract_dsnId_fkey" FOREIGN KEY ("dsnId") REFERENCES "Dsn"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkContract" ADD CONSTRAINT "WorkContract_dsnId_establishmentId_numSS_fkey" FOREIGN KEY ("dsnId", "establishmentId", "numSS") REFERENCES "Person"("dsnId", "establishmentId", "numSS") ON DELETE CASCADE ON UPDATE CASCADE;
